name: peers_touch_base
description: "Peers Touch Base Library - Shared Dart library for AI functionality"
version: 0.0.1
homepage:

environment:
  sdk: ^3.8.0

dependencies:
  protobuf: ^5.1.0
  crypto: ^3.0.3
  pointycastle: ^3.7.3
  cryptography: ^2.7.0
  dio: ^5.4.3+1
  dio_smart_retry: ^7.0.1
  logging: ^1.2.0
  fixnum: ^1.1.0
  drift: any
  path: ^1.8.3
  synchronized: ^3.4.0
  stack_trace: ^1.12.1
  uuid: ^4.5.2
  buffer: ^1.2.3
  async: ^2.11.0
  dcid: ^1.0.0
  mdns_dart: ^2.0.1
  bs58: ^1.0.2
  dart_multihash: ^1.0.1
  cid: ^1.0.1

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
  mockito: ^5.4.4
  build_runner: ^2.4.9
